---
- hosts: all
  become: true
  tasks: 
  - name: "install apache package"
    apt: 
      name: apache2
  - name: disable service apache2, and not touch the state
    ansible.builtin.service:
      name: apache2
      enabled: false
  - name: disable service apache2, and not touch the state
    ansible.builtin.service:
      name: apache2
      state: stopped
